###
DELETE http://localhost:3001/api/notes/1

###
GET http://localhost:3001/api/notes

###
GET http://localhost:3001/api/notes/623d7e6b7995ba954da2d2dd

### 
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "lol, I love programming!"
}


###
PUT http://localhost:3001/api/notes/6246b261ff4a2ae3ad3df3d3
Content-Type: application/json

{
    "important": true
}

