###
DELETE http://localhost:3001/api/persons/1

###
GET http://localhost:3001/api/persons

### 
POST https://still-bird-6039.fly.dev/api/persons
Content-Type: application/json

{
    "name": "Shrek",
    "number": "2348-2342"
}

###
GET https://still-bird-6039.fly.dev/api/persons