###
DELETE http://localhost:3001/api/notes/1

###
GET http://localhost:3001/api/blogs

###
GET http://localhost:3001/api/blogs/637b1edb1daa288b4565abe4

### 
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Getting Acquainted With Blender For 3D Modeling",
    "author": "Brian M.",
    "url": "http://localhost:3001/",
    "likes": "10"
}


###
PUT http://localhost:3001/api/blogs/637b1edb1daa288b4565abe4
Content-Type: application/json

{
    "likes": "11"
}

